export enum IPC_EVENT {
    APP_READY = 'app-ready',
    APP_REFRESH = 'app-refresh',
    GET_CONFIG = 'get-config',
    SET_CONFIG = 'set-config',
    NEW_SAVE = 'new-save',
    LOAD_SAVE = 'load-save',
    OPEN_CONFIG = 'open-config',
    BACKUP_CONFIG = 'backup-config',
    LOAD_BACKUP_CONFIG = 'load-backup-config',
    GET_SAVE = 'get-save',
    SET_SAVE = 'set-save',
    OPEN_SAVE = 'open-save',
    BACKUP_SAVE = 'backup-save',
    LOAD_BACKUP_SAVE = 'load-backup-save',
    GET_DATA = 'get-data',
    IMPORT_CUSTOM = 'import-custom',
    EXPORT_CUSTOM = 'export-custom',
    SEARCH_CONSOLE_GAMES = 'search-console-games',
    SEARCH_GAMER_ESCAPE = 'search-gamer-escape',
    SEARCH_GARLAND_TOOLS = 'search-garland-tools',
    OPEN_IN_GARLAND_TOOLS = 'open-in-garland-tools',
    OPEN_IN_TEAMCRAFT = 'open-in-teamcraft'
}
