export const GROUP_MAP = [
    { groups: ['Quests', 'Levequests'], firstTask: 'A Long and Winding Road', extraCompare: LeveCompare },
    { groups: ['Quests', 'Levequests'], firstTask: 'Waking Wood', extraCompare: LeveCompare },
    { groups: ['Quests', 'Levequests'], firstTask: 'One for the Books', extraCompare: LeveCompare },
    { groups: ['General Logs', 'Blue Mage', 'Spellbook'], firstTask: 'Water Cannon' },
    { groups: ['General Logs', 'Blue Mage'], firstTask: '' }, //TODO: Blue Mage Logs?
    { groups: ['General Logs', 'Blue Mage', 'The Masked Carnivale'], firstTask: 'All\'s Well That Starts Well' },
    { groups: ['General Logs', 'Hunting Log'], firstTask: 'Little Ladybug x3' },
    { groups: ['General Logs', 'Sightseeing Log'], firstTask: 'Barracuda Piers' },
    { groups: ['Crafting Log', 'Carpenter'], firstTask: 'Maple Lumber' },
    { groups: ['Crafting Log', 'Blacksmith'], firstTask: 'Bronze Ingot' }, //TODO:
    { groups: ['Crafting Log', 'Armorer'], firstTask: 'Bronze Ingot' }, //TODO:
    { groups: ['Crafting Log', 'Goldsmith'], firstTask: 'Copper Ingot' },
    { groups: ['Crafting Log', 'Leatherworker'], firstTask: 'Leather' },
    { groups: ['Crafting Log', 'Weaver'], firstTask: 'Hempen Yarn' },
    { groups: ['Crafting Log', 'Alchemist'], firstTask: 'Distilled Water' },
    { groups: ['Crafting Log', 'Culinarian'], firstTask: 'Table Salt' },
    { groups: ['Crafting Log', 'Shared'], firstTask: 'Magitek Repair Materials' },
    { groups: [['Gathering Log', 'Mining'], ['Gathering Log', 'Quarrying']], firstTask: 'Copper Ore' },
    { groups: ['Gathering Log', 'Logging'], firstTask: 'Latex' }, //TODO: Harvesting?
    { groups: [['Gathering Log', 'Fishing', 'Log'], ['Gathering Log', 'Spearfishing', 'Log']], firstTask: 'Limsa Lominsa Upper Decks' },
    { groups: [['Gathering Log', 'Fishing', 'Guide'], ['Gathering Log', 'Spearfishing', 'Guide']], firstTask: 'Malm Kelp' },
    { groups: ['Collectables', 'Aesthetician'], firstTask: 'Adventure' },
    { groups: ['Collectables', 'Emotes'], firstTask: 'Aback' },
    { groups: ['Collectables', 'Minion Guide'], firstTask: 'Abroader Otter' },
    { groups: [['Collectables', 'Barding'], ['Collectables', 'Mount Guide']], firstTask: 'Adamantoise' },
    { groups: ['Collectables', 'Relic Gear'], firstTask: 'Artemis Bow' },
    { groups: ['Collectables', 'Orchestrion List'], firstTask: 'Wailers and Waterwheels' },
    { groups: ['Collectables', 'Triple Triad Card List'], firstTask: 'Ahriman Card', extraCompare: TripleTriadCardCompare },
    { groups: ['Collectables', 'Triple Triad Card Opponent'], firstTask: 'Triple Triad Master' },
    { groups: ['Quests', 'Main Scenario', 'Seventh Umbral Era'], firstTask: 'Close to Home' },
    { groups: ['Quests', 'Main Scenario', 'Seventh Astral Era'], firstTask: 'The Price of Principles' },
    { groups: ['Quests', 'Main Scenario', 'Heavensward'], firstTask: 'Coming to Ishgard' },
    { groups: [['Quests', 'Main Scenario', 'Dragonsong'], ['Quests', 'Main Scenario', 'Post-Dragonsong']], firstTask: 'An Uncertain Future' },
    { groups: ['Quests', 'Main Scenario', 'Stormblood'], firstTask: 'Beyond the Great Wall' },
    { groups: ['Quests', 'Main Scenario', 'Post-Stormblood'], firstTask: 'Arenvald\'s Adventure' },
    { groups: ['Quests', 'Main Scenario', 'Shadowbringers'], firstTask: 'The Syrcus Trench' },
    { groups: ['Quests', 'Main Scenario', 'Post-Shadowbringers'], firstTask: 'Shaken Resolve' },
    { groups: ['Quests', 'Sidequests', 'Lominsan'], firstTask: 'Coming to Limsa Lominsa' },
    { groups: ['Quests', 'Sidequests', 'Gridanian'], firstTask: 'Coming to Gridania' },
    { groups: ['Quests', 'Sidequests', 'Ul\'Dahn'], firstTask: 'Coming to Ul\'dah' },
    { groups: ['Quests', 'Sidequests', 'Coerthan'], firstTask: 'Leves of the Observatorium' },
    { groups: ['Quests', 'Sidequests', 'Mor Dhonan'], firstTask: 'A Legend for a Legend' },
    { groups: ['Quests', 'Sidequests', 'Ishgardian'], firstTask: 'Remembering Ishgard' },
    { groups: [['Quests', 'Sidequests', 'Abalathian'], ['Quests', 'Sidequests', 'Azys Lla']], firstTask: 'The Way of the Dodo' },
    { groups: ['Quests', 'Sidequests', 'Dravanian'], firstTask: 'Some Bad News' },
    { groups: ['Quests', 'Sidequests', 'Gyr Abanian'], firstTask: 'Magiteknical Failure' },
    { groups: ['Quests', 'Sidequests', 'Othardian'], firstTask: 'Knocking on Heaven\'s Door' },
    { groups: ['Quests', 'Sidequests', 'Hingan'], firstTask: 'A Lone Wolf No More' },
    { groups: ['Quests', 'Sidequests', 'Lakeland'], firstTask: 'Classical Condition' },
    { groups: ['Quests', 'Sidequests', 'Kholusia'], firstTask: 'A Clam to Die For' },
    { groups: ['Quests', 'Sidequests', 'Amh Araeng'], firstTask: 'And Justice Feral' },
    { groups: ['Quests', 'Sidequests', 'Il Mheg'], firstTask: 'A New Amano' },
    { groups: ['Quests', 'Sidequests', 'Rak\'Tika'], firstTask: 'An Express Delivery' },
    { groups: ['Quests', 'Sidequests', 'Tempest'], firstTask: 'Beware the Benthos' },
    { groups: [['Duty', 'Hall of the Novice'], ['Quests', 'Class & Job']], firstTask: 'Avoid Area of Effect Attacks' },
    { groups: ['Quests', 'Class & Job'], firstTask: 'A Song of Bards and Bowmen' },
    { groups: ['Quests', 'Class & Job', 'Role'], firstTask: 'The Man with Too Many Scars' },
    { groups: ['Quests', 'Class & Job', 'Crystalline Mean'], firstTask: 'The Crystalline Mean' },
    { groups: ['Quests', 'Chronicles of a New Era'], firstTask: 'A Recurring Problem' },
    { groups: ['Quests', 'Sidequests', 'Side Story'], firstTask: 'The Rise and Fall of Gentlemen' },
    { groups: ['Quests', 'Beast Tribe'], firstTask: 'Peace for Thanalan' },
    { groups: ['Quests', 'Other', 'Grand Company'], firstTask: 'A Pup No Longer (Maelstrom)' },
    { groups: [['Duty', 'Guildhests'], ['Duty', 'Dungeons']], firstTask: 'Basic Training: Enemy Parties' },
    { groups: ['Duty', 'Raids'], firstTask: 'The Binding Coil of Bahamut - Turn 1' },
    { groups: ['Duty', 'Trials'], firstTask: 'The Bowl of Embers' },
    { groups: ['Duty', 'The Hunt'], firstTask: 'Albin the Ashen' },
    { groups: ['FATEs', 'La Noscea'], firstTask: 'I Melt with You' },
    { groups: ['FATEs', 'The Black Shroud'], firstTask: 'One Enchanted Eve' },
    { groups: ['FATEs', 'Thanalan'], firstTask: 'Let them Eat Cactus' },
    { groups: ['FATEs', 'Coerthas'], firstTask: 'Twelve Ilms of Snow' },
    { groups: ['FATEs', 'Mor Dhona'], firstTask: 'Mud About You' },
    { groups: ['FATEs', 'Abalathia\'s Spine'], firstTask: 'Food Fight (FATE)' },
    { groups: ['FATEs', 'Dravania'], firstTask: 'Glawackus On, Glawackus Off' },
    { groups: ['FATEs', 'Gyr Abania'], firstTask: 'Bold This Way' },
    { groups: ['FATEs', 'Othard'], firstTask: 'Agni\'s Philosophy' },
    { groups: ['FATEs', 'Eureka'], firstTask: 'Unsafety Dance' },
    { groups: ['FATEs', 'Norvrandt'], firstTask: 'A Beast Among Men' },
    { groups: ['Travel', 'Aether Currents'], firstTask: 'Twinpools' },
    { groups: ['Travel', 'Mount Speed'], firstTask: 'Mist' },
    { groups: ['', ''], firstTask: '' }, //TODO: Shared FATE?
    { groups: ['Travel', 'Porters'], firstTask: 'Limsa Lominsa Lower Decks' },
    { groups: ['Achievements', 'Battle'], firstTask: 'To Crush Your Enemies I' },
    { groups: ['Achievements', 'PvP'], firstTask: 'Cutting Your Wolf Loose: Maelstrom I' },
    { groups: ['Achievements', 'Character'], firstTask: 'Mastering War I' },
    { groups: ['Achievements', 'Items'], firstTask: 'My Body Is a Temple' },
    { groups: ['Achievements', 'Crafting & Gathering'], firstTask: 'I Made That: Carpenter I' },
    { groups: ['Achievements', 'Quest'], firstTask: 'Serving a Greater Cause I' },
    { groups: ['Achievements', 'Exploration'], firstTask: 'Out of Sight' },
    { groups: ['Achievements', 'Grand Company'], firstTask: 'I Make This Look Good' },
];

function LeveCompare(isMatch, appTask, sheetTaskName) {
    return isMatch || appTask.name === `${sheetTaskName} (L)`;
}

function TripleTriadCardCompare(isMatch, appTask, sheetTaskName) {
    return isMatch || sheetTaskName === `${appTask.name} Card`;
}
